apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-calculator-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-calculator-api
    spec:
      containers:
      - name: azure-calculator-api
        image: benlamregistry1.azurecr.io/calculator:v1.0-34-g9ef5eb4
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
      imagePullSecrets:
      - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: azure-calculator-api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: azure-calculator-api